# Generated by Django 5.0.1 on 2024-01-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inse', '0002_rename_item_inse'),
    ]

    operations = [
        migrations.AddField(
            model_name='inse',
            name='co_municipio',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inse',
            name='co_uf',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inse',
            name='id_escola',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inse',
            name='media_inse',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='inse',
            name='nu_ano_saeb',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inse',
            name='pc_nivel_1',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='inse',
            name='pc_nivel_2',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='inse',
            name='pc_nivel_3',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='inse',
            name='pc_nivel_4',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='inse',
            name='pc_nivel_5',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='inse',
            name='pc_nivel_6',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='inse',
            name='pc_nivel_7',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='inse',
            name='pc_nivel_8',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='inse',
            name='qtd_alunos_inse',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inse',
            name='tp_capital',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inse',
            name='tp_localizacao',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inse',
            name='tp_tipo_rede',
            field=models.IntegerField(default=0),
        ),
    ]
